### PR TITLE
Compiles and tests pass now

### PR DESCRIPTION
**Pull request by singpolyma**
Tests build and pass!

### CODE REVIEW

**Comment by LukasKalbertodt** [comment]
Is anything happening here? Why isn't this merged? Would be a shame if this project is bit rotting...

**Comment by jruhland** [comment]
Sorry about that, I thought I had merged it

**Comment by LukasKalbertodt** [comment]
:+1: Thanks! You said here (#124) that the reason for not uploading it to `crates.io` is that it doesn't compile. So it would be ready for publishing now, right?

**Comment by jruhland** [comment]
https://crates.io/crates/rustache

Has been published.  Huge thanks to @singpolyma for all his work getting this thing running again.

**Pull request merged**
